generate_joke_task:
  description: >
    Generate 10 jokes about Chuck Norris
  expected_output: >
    A list with 10 Chuck Norris Jokes 
  agent: chuck_norris_joke_generator

pick_joke_task:
  description: >
    pick the best joke from a list of jokes.
  expected_output: >
    The best joke from a list of jokes
  agent: chuck_norris_joke_picker
